# Generated by Django 4.1.7 on 2023-03-14 22:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_account_user_budget_user_transaction_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='WalletAccount',
        ),
    ]
