# Generated by Django 4.1.7 on 2023-03-14 22:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_rename_account_walletaccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WalletAccount',
            new_name='Account',
        ),
    ]
